# Project name: Code Blue
# Description: This project assists the homeless during cold weather
# Filename: reports_controller.rb
# Description: Controller for report model, code is autogenerated
#              unless otherwise noted
# Last modified on: 1 May 2020
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  # This method is edited, it creates a location object which calls a validator
  def create
    #location_string = report_params['location_string'] # get street input
    #location = Location.new() 
    # add location to report_params, remove location_string
    @report = Report.new(report_params) # create a report object

    respond_to do |format|
      if @report.save
        format.html { redirect_to :root, notice: 'Report was successfully created.' }
        #format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # EDIT: change required parameters for reference objects
    def report_params
      #params.require(:report).permit(:numPeople, :comments)#(:location_id, :weather_id, :numPeople, :comments)
      params.fetch(:report).permit(:numPeople, :comments)
    end
end
